import PropTypes from 'prop-types'

export const canvasShape = PropTypes.shape({
  add: PropTypes.func,
  backgroundColor: PropTypes.string,
  defaultCursor: PropTypes.string,
  discardActiveObject: PropTypes.func,
  findTarget: PropTypes.func,
  fire: PropTypes.func,
  fxRemove: PropTypes.func,
  getActiveObject: PropTypes.func,
  getActiveObjects: PropTypes.func,
  getCenter: PropTypes.func,
  getHeight: PropTypes.func,
  getObjects: PropTypes.func,
  getPointer: PropTypes.func,
  getWidth: PropTypes.func,
  getZoom: PropTypes.func,
  height: PropTypes.number,
  off: PropTypes.func,
  on: PropTypes.func,
  remove: PropTypes.func,
  renderAll: PropTypes.func,
  requestRenderAll: PropTypes.func,
  selection: PropTypes.bool,
  sendToBack: PropTypes.func,
  setActiveObject: PropTypes.func,
  setBackgroundColor: PropTypes.func,
  setBackgroundImage: PropTypes.func,
  setCursor: PropTypes.func,
  setHeight: PropTypes.func,
  setViewportTransform: PropTypes.func,
  setWidth: PropTypes.func,
  setZoom: PropTypes.func,
  viewportTransform: PropTypes.arrayOf(PropTypes.number),
  width: PropTypes.number,
  zoom: PropTypes.number,
  zoomToPoint: PropTypes.func
})
