
import { COLORS } from '@/theme/theme.default'

const themeKey = {
  DEFAULT_BACKGROUND: 'base00',
  LIGHTER_BACKGROUND: 'base01',
  SELECTION_BACKGROUND: 'base02',
  COMMENTS: 'base03',
  DARK_FOREGROUND: 'base04',
  DEFAULT_FOREGROUND: 'base05',
  LIGHT_FOREGROUND: 'base06',
  LIGHT_BACKGROUND: 'base07',
  VARIABLES: 'base08',
  INTEGERS_BOOLEAN_CONSTANTS: 'base09',
  CLASSES: 'base0A',
  STRINGS: 'base0B',
  REGULAR_EXPRESSIONS: 'base0C',
  ATTRIBUTE_IDS: 'base0D',
  KEYWORDS_STORAGE_SELECTOR: 'base0E',
  NUMBERS: 'base0F'
}

const jsonThemeConfig = {
  [themeKey.DEFAULT_BACKGROUND]: COLORS.PRIMARY_3,
  [themeKey.LIGHTER_BACKGROUND]: COLORS.SUCCESS,
  [themeKey.SELECTION_BACKGROUND]: COLORS.ERROR_BG,
  [themeKey.COMMENTS]: COLORS.GRAYSCALE_3,
  [themeKey.DARK_FOREGROUND]: COLORS.GRAYSCALE_3,
  [themeKey.DEFAULT_FOREGROUND]: COLORS.ERROR,
  [themeKey.LIGHT_FOREGROUND]: COLORS.GRAYSCALE_3,
  [themeKey.LIGHT_BACKGROUND]: COLORS.ERROR,
  [themeKey.VARIABLES]: COLORS.GRAYSCALE_3,
  [themeKey.INTEGERS_BOOLEAN_CONSTANTS]: COLORS.SUCCESS,
  [themeKey.CLASSES]: COLORS.PRIMARY_4,
  [themeKey.STRINGS]: COLORS.PRIMARY_2,
  [themeKey.REGULAR_EXPRESSIONS]: COLORS.GRAYSCALE_4,
  [themeKey.ATTRIBUTE_IDS]: COLORS.GRAYSCALE_4,
  [themeKey.KEYWORDS_STORAGE_SELECTOR]: COLORS.GRAYSCALE_3,
  [themeKey.NUMBERS]: COLORS.NUMBERS_IN_JSON
}

export {
  jsonThemeConfig
}
