export * from './Table'
export * from './Cell'
export * from './tableSchema'
export * from './CellsMerge'
export * from './CellValue'

export { addColumn } from '@/models/Table/addColumn'
export { addRow } from '@/models/Table/addRow'
export { autoMerge } from '@/models/Table/autoMerge'
export { deleteColumn } from '@/models/Table/deleteColumn'
export { deleteRow } from '@/models/Table/deleteRow'
export { divide } from '@/models/Table/divide'
export { getCells } from '@/models/Table/getCells'
export { getBorders } from '@/models/Table/getBorders'
export { getDimensions } from '@/models/Table/getDimensions'
export { getPosition } from '@/models/Table/getPosition'
export { getSize } from '@/models/Table/getSize'
export { moveBorder } from '@/models/Table/moveBorder'
export { move } from '@/models/Table/move'
export { getMergeProjection, mergeCells } from '@/models/Table/mergeCells'
export { resizeColumnOrRow } from '@/models/Table/resizeColumnOrRow'
export { setPosition } from '@/models/Table/setPosition'
export { toAbsolute, toRelative } from '@/models/Table/cordConvert'
export { getSplitProjection, splitCells } from '@/models/Table/splitCells'
