name: "Checking: Lint + Test + Dev Build"
on:
  push:
    paths:
      - "*/**.js"
      - "*/**.jsx"
      - "*/**.json"
      - "*/**.html"
  pull_request: {}
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn

      -
        name: Install dependencies
        run: yarn install --pure-lockfile

      -
        name: Run ESLint and Stylelint
        run: yarn lint

      -
        name: Run tests
        run: yarn test:ci

      -
        name: Test Summary
        uses: test-summary/action@v2
        if: always()
        with:
          paths: "reports/report.xml"

      -
        name: Test Dev build
        run: yarn build:dev
